export const myProjects = [
  {
    title: "Doctor Nibras",
    description: `A modern medical portfolio website for Dr. Nibras, built with HTML, CSS, and JavaScript. Features a clean, professional design with responsive layouts and smooth animations.`,
    category: ["css", "company_tasks"],
    imgPath: "./doctor-nibras.png",
    githubURL: "https://github.com/kinan-sleman/Doctor-Alogaidi",
    link: "https://kinan-sleman.github.io/Doctor-Alogaidi/",
  },
  {
    title: "Leon Template",
    description: `A sleek, responsive landing page template built with HTML and CSS. Features modern design elements, smooth animations, and a fully responsive layout.`,
    category: ["css"],
    imgPath: "./leon-template.png",
    githubURL: "https://github.com/kinan-sleman/Leon-Template",
    link: "https://kinan-sleman.github.io/Leon-Template/",
  },
  {
    title: "Front-end Test",
    description: `A comprehensive front-end test for BookSMM Company, built with React.js and pure CSS. Features a modern UI with interactive components and responsive design.`,
    category: ["css", "react", "company_tasks"],
    imgPath: "./front-end-test.png",
    githubURL: "https://github.com/kinan-sleman/front-end-test",
    link: "https://front-end-test50.netlify.app/",
  },
  {
    title: "NestJS Blog API",
    description: `A scalable backend for a blogging platform built with NestJS and TypeScript. Features user authentication (JWT), articles management (CRUD), personalized feeds, and profile interactions (follow/unfollow).`,
    category: ["nest"],
    imgPath: "./nest-blog.png",
    githubURL: "https://github.com/kinan-sleman/nestjs-crashcourse",
    link: "https://nest-blog-production-0709.up.railway.app/api#/",
  },
  // {
  //   title: "Giphy Search app",
  //   description: `This app is designed to search for GIFs and copy their URLs for use in various projects. It streamlines the process of finding, selecting, and sharing animated images, making it quick and efficient for users.`,
  //   category: ["vue"],
  //   imgPath: "./giphy.png",
  //   githubURL: "https://github.com/kinan-sleman/giphy-api",
  //   link: "https://kinan-sleman.github.io/giphy-api/",
  // },
  // {
  //   title: "Todo List app",
  //   description: `This Vue and Vuex-based app is designed to manage a to-do list. It allows users to add, edit, and delete tasks efficiently while maintaining state management.`,
  //   category: ["vue"],
  //   imgPath: "./todoVue.png",
  //   githubURL: "https://github.com/kinan-sleman/vuejs-todo-list",
  //   link: "https://kinan-sleman.github.io/vuejs-todo-list/",
  // },
  {
    title: "Nexcent",
    description: `Nexcent - A corporate landing page for Oona Tech, built with TypeScript, React.js, and Tailwind CSS. Features smooth Framer Motion animations and a professional design.`,
    category: ["company_tasks", "react"],
    imgPath: "./nexcent.png",
    githubURL: "https://github.com/kinan-sleman/nexcent",
    link: "https://kinan-sleman.github.io/nexcent/",
  },
  {
    title: "Shopsy",
    description: `Shopsy - A modern e-commerce platform built with React.js and Tailwind CSS. Features AOS animations for enhanced user experience and a responsive shopping interface.`,
    category: ["react"],
    imgPath: "./shopsy.png",
    githubURL: "https://github.com/kinan-sleman/shopsy",
    link: "https://shopsy-50.netlify.app",
  },
  {
    title: "eShop",
    description: `eShop - A full-featured e-commerce platform built with React.js, TypeScript, and Tailwind CSS. Includes secure Firebase Authentication and a modern shopping experience.`,
    category: ["react"],
    imgPath: "./eShop.png",
    githubURL: "https://github.com/kinan-sleman/eShop",
    link: "https://eshop-50.netlify.app",
  },
  {
    title: "Movie Finder",
    description: `A modern movie discovery platform built with React.js, Vite, Bootstrap, and TypeScript. Utilizes Context API for state management, featuring a sleek UI for searching movies, viewing details, and managing favorites. Perfect for movie enthusiasts and casual viewers alike.`,
    category: ["react"],
    imgPath: "./movie-finder.png",
    githubURL: "https://github.com/kinan-sleman/movie-finder",
    link: "https://movie-finder-50.netlify.app",
  },
  // {
  //   title: "Oona Tech Website",
  //   description: `This is the main Website for Oona Tech company that created by React.js, TypeScript, Redux Toolkit and Tailwind CSS`,
  //   category: ["react"],
  //   imgPath: "./Oona Tech Website.png",
  //   githubURL: "https://github.com/kinan-sleman/oona-tech-website",
  //   link: "https://66e2699c2adcdce22ea0d140--papaya-empanada-e4fd4d.netlify.app/",
  // },
];
